### ISSUE TITLE
Build it

### ISSUE THREAD

**Issue by szepeviktor** [DonKult/dotPageMod#1]
Maybe a Docker container to build your addon?

**Comment by DonKult** [comment]
What would be the point? Building the add-on needs "pandoc" and "zip" – or more general something which can convert markdown text to html (to convert the README, not _that_ mission critical…)¹ and something which packs a bunch of files in a zip file (which xpi files are). Even ignoring that, you need the source anyhow as you have to 'install' the app (if only by downloading the source). So I am not sure what the benefit would be, but I would be happy to be enlightened – perhaps I am just routine-blinded.

¹ yes, pandoc is kinda heavy-weight. Any other markdown converter would do just as well, it's just the first I thought of and is used relatively often, so more likely installed than others might and if not just an apt-get (or equivalent in another distro) away.

**Comment by szepeviktor** [comment]
Only for providing an XPI file.
Usually it is provided with the release, but I do not see any releases here on GitHub.
